#ARG BUILD_FROM

#FROM ${BUILD_FROM}

FROM eightiesguy/headphones-addon

# modify/copy files

#RUN sed -i "s|config|data|g" /etc/cont-init.d/*

#RUN sed -i "s|config|data|g" /etc/services.d/headphones/*

#COPY root/ /

#VOLUME ["/share", "/ssl", "/data", "/media"]
