FROM linuxserver/headphones

ENV XDG_DATA_HOME="/data" \
XDG_CONFIG_HOME="/data"

# modify/copy files

RUN sed -i "s|config|data|g" /etc/cont-init.d/*

RUN sed -i "s|config|data|g" /etc/services.d/headphones/*

COPY root/ /

VOLUME ["/share", "/ssl", "/data"]
