#ARG BUILD_FROM

#FROM ${BUILD_FROM}
FROM eightiesguy/sickchill-addon:2021.3.10

#ENV XDG_DATA_HOME="/data" \
#XDG_CONFIG_HOME="/data"

# modify/copy files

#RUN sed -i "s|config|data|g" /etc/cont-init.d/*

#RUN sed -i "s|config|data|g" /etc/services.d/sickchill/*

#RUN rm -r /media

#VOLUME ["/share", "/ssl", "/data", "/media"]
