#ARG BUILD_FROM

FROM emby/embyserver_arm32v7:4.6.0.37

ARG BUILD_ARCH

LABEL io.hass.version="4.6.0.37" io.hass.type="addon" io.hass.arch="${BUILD_ARCH}"

#RUN sed -i "s|config|data|g" /etc/services.d/emby-server/run

RUN ["sed", "-i", "s|config|data|g", "/etc/services.d/emby-server/run"]

VOLUME ["/share", "/data", "/media"]
